name = "OAuth"
uuid = "818da804-8b6f-40df-b4a5-e161c4d67f0f"
version = "1.0.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibAwsCal = "ef519ef6-af43-41a0-8ac4-eb81328190af"
LibAwsCommon = "c6e421ba-b5f8-4792-a1c4-42948de3ed9d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"

[compat]
HTTP = "1"
JSON = "1"
LibAwsCal = "1.1"
LibAwsCommon = "1.3.4"
julia = "1.10"
libsodium_jll = "1.0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
